### ISSUE TITLE
bioc2023 plan

### ISSUE THREAD

**Issue by mikelove** [tidyomics/tidyomicsWorkshop#3]
@stemangiola I think for bioc2023 you could go first and introduce TT and then I can go second and show e.g. using plyranges to compute on the single cell data. E.g. looking at relation of genes to other features, or to genomic tiles, just something that uses the locations + plyranges + maybe nullranges.

**Comment by mikelove** [comment]
Which vignette do you think you will choose? SCE (PBMC)?

I will think of some operations to perform on the PBMC data, maybe I can use blood epigenetic marks in AHub, e.g.

```
"UCSF-UBC.Peripheral_Blood_Mononuclear_Primary_Cells.H3K27ac.TC015.broadPeak.gz"
```

**Comment by stemangiola** [comment]
I think [single_cell_bioconductor_transcriptomics.Rmd](https://github.com/tidybiology/tidyomicsWorkshop/blob/devel/vignettes/single_cell_bioconductor_transcriptomics.Rmd)

But happy to adapt to the best dataset you think.

**Comment by mikelove** [comment]
Note to self: H3K4me3 for PBMC from Roadmap has good signal, probably use the two narrowPeak tracks here:

```
query(ah, c("Peripheral_Blood","h3k4me3"))
```

Rough idea would be to work downstream from the SCE tasks, show that we can calculate distance from strong peaks in ChIP-seq to the genes. Maybe they tend to be highly expressed or even marker genes for cell types in PBMC data? Hint about using bootRanges or matchRanges to form hypotheses and test them.

**Comment by mikelove** [comment]
I will work on adding a simple genomic related example to the end and then we can work on trimming it down to 45 minutes worth?

https://tidybiology.github.io/tidyomicsWorkshop/articles/single_cell_bioconductor_transcriptomics.html

We should credit Maria Doyle in the workshop author list, and anyone else who contributed.

**Comment by mikelove** [comment]
Should we trim down the `DESCRIPTION` and required installs in README to just the essentials for this workshop (and then we can build out later in branches to cover all the workshops)?

```
    SummarizedExperiment, 
    SingleCellExperiment,
    tidySummarizedExperiment,
    tidySingleCellExperiment,
    tidygate,
    stats,
    utils,
    tibble,
    stringr,
    ggplot2,
    dplyr,
    readr,
    tidyr,
    purrr,
    forcats,
    ggrepel,
    plotly,
    igraph,
    broom,
    devtools,
    rlang,
    magrittr,
    R.utils,
    dittoSeq,
    tidybulk,
    glue,
    scater,
    batchelor
```

The package loads currently only:

```
    SingleCellExperiment
    tidySingleCellExperiment
    ggplot2
    plotly
    dplyr
    colorspace
    dittoSeq,
    scater,
    batchelor
    purrr
```

**Comment by stemangiola** [comment]
I see. My understanding was that we would have the master branch with all possible vignettes and all possible dependencies used for those vignettes, and we would create branches for each single workshop, for example Bioc2023 where we would trim the vignettes and dependencies.

Or should we have a different organisation?

**Comment by mikelove** [comment]
Let's see. I was having trouble getting GitHub Actions to pass check due to Seurat dependencies, but everything currently is easily reversible (remove `eval=FALSE` from those vignettes, move Seurat objects back into `data/` and uncomment the roxygen chunks in `R/`).

Now that I think about it, the way the GitHub Actions work, it's one website per repository. I don't know how we would do it per branch after all.

Thoughts? I'm tempted to just resort to the easy (old) solution:

* `tidyomicsWorkshop` has all the vignettes - someone will have to get GitHub actions working for this at a later date, resolving the issues with Seurat
* `tidyomicsWorkshopBioc2023` is the trimmed down one for this upcoming workshop, just the Bioc SCE example and dependencies

**Comment by stemangiola** [comment]
Uhh, I liked the idea of repo and branches! We can do this for this workshop.
 However, I believe would be possible to create branch-specific websites, where the website name is defined in the github action, which itself is specific for each branch.
 
 It would be just change the website name when we change the workshop branch.
 
 @mblue9 does it sound feasible?

**Comment by mikelove** [comment]
Oh great, yeah I would _much_ prefer to have a single repo with branch-specific website and docker builds from branch-specific GHA.

If we can quickly figure that out (I don't have much bandwidth to do it unfortunately), I'm all in favor. But I have to start working on workshop material next week and the following week.

**Comment by stemangiola** [comment]
It seems it's not feasible :(

https://stackoverflow.com/questions/72534312/is-there-a-way-to-create-different-webpages-with-each-branch-in-one-repo-using-g#:~:text=You%20cannot%20have%20separate%20sites,when%20publishing%20your%20Pages%20site.

How about building a vignette (website tab) for each workshop? Do you think it's not scalable?

**Comment by stemangiola** [comment]
Otherwise we can do a separate repo (which is also the strategy I always used)

**Comment by mikelove** [comment]
The problems with vignette per workshop are that each vignette needs to get built for the GHA workflows, and all packages must go into `DESCRIPTION`. Meaning, if one vignette has a dependency that's causing an issue, you can't successfully deploy another workshop until you've fixed that issue.

Unfortunately, I think separate repo per workshop is the only remaining alternative, but at least then we can get going with BioC2023 material. We can merge changes/updates back into the main repo `tidyomicsWorkshop` at appropriate times.

So I will make a duplicate repo and trim it down for our upcoming workshop. What naming scheme?

* `tidyomicsWorkshopBioc2023`
* `bioc2023TidyomicsWorkshop`
* other?

**Comment by stemangiola** [comment]
I like 

tidyomicsWorkshop

for the template and 

tidyomicsWorkshopBioc2023

For the specific ones


Or 

tidyomicsWorkshopTemplate

which stays private, and we publish the specific ones?

Not sure if the current naming can be confusing for users. Happy to follow your lead.

**Comment by mikelove** [comment]
I'll work on copying current material over to `tidyomicsWorkshopBioc2023`, getting that building properly, and trimming to essential packages and vignette.

We can fix up the template at a later date, I can reverse my changes etc.

**Comment by mikelove** [comment]
Ok this repo is now reversed to its old form, but I didn't bother with the GHA bc I it will need adjusting wrt Seurat.

Moving to https://github.com/tidybiology/tidyomicsWorkshopBioc2023/issues/1
