### ISSUE TITLE
Package python is not available

### ISSUE THREAD

**Issue by mikelove** [tidyomics/tidyomicsWorkshop#4]
```
Package python is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  2to3 python2-minimal python2 dh-python python-is-python3

E: Package 'python' has no installation candidate
Error: Process completed with exit code 100.
```

https://github.com/tidybiology/tidyomicsWorkshop/actions/runs/5330356013/jobs/9656956305

**Comment by mikelove** [comment]
@stemangiola have you surmounted this before?

**Comment by stemangiola** [comment]
Github actions drive my crazy. @mblue9 is the expert here :) Maria, did you solve this before?

**Comment by mblue9** [comment]
Hey! I think @michaelplynch may have encountered this one

**Comment by michaelplynch** [comment]
This might be worth a try: https://github.com/michaelplynch/demultiplexing-bioc23/blob/main/.github/workflows/basic_checks.yaml
Its my solution for the trouble the standard buildabiocworkshop actions was having with reticulate based dependencies.

**Comment by mikelove** [comment]
Ok, I removed the Seurat-related vignettes (`eval=FALSE`) and data objects (`seurat_data/`) and now the package builds and checks fine.
